source 'https://rubygems.org'

gem 'middleman-core'
gem 'middleman-sprockets'

# Live-reloading plugin
# gem 'middleman-livereload'

# For faster file watcher updates on Windows:
gem 'wdm', '~> 0.1.0', :platforms => [:mswin, :mingw]

# Windows does not come with time zone data
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]

# Use Haml templates
gem 'haml'

# Use Sass stylesheets
gem 'sass'

# Use bourbon Sass maxins
gem 'bourbon'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier'

# Use kramdown markdown parser
gem 'kramdown'
